### ISSUE TITLE
luckjacksonn/grade50 --> raphaelrk/grade50

### ISSUE THREAD

**Issue by raphaelrk** [raphaelrk/grade50#1]
Seems like ownership still hasn't transferred, would like for it to be under my name if possible :)

**Comment by lukejacksonn** [comment]
Have you accepted the transfer?

**Comment by lukejacksonn** [comment]
<img width="730" alt="screen shot 2016-10-03 at 7 50 05 pm" src="https://cloud.githubusercontent.com/assets/1457604/19058102/b59e96b0-89a2-11e6-8acc-14386b852802.png">

This seems to be my only option at the moment

**Comment by raphaelrk** [comment]
Had to accept it via a link sent to my email, thanks Luke!
